### ISSUE TITLE
Issue with proxies

### ISSUE THREAD

**Issue by entrptaher** [jmendeth/curl-benchmark#2]
It's not producing any result when passing proxy using `-x`,

```
➜  curl-benchmark git:(master) python3 curl-benchmark.py "http://example.com"                   
              DNS      TCP        SSL  Request          Content
     Code  lookup  connect  handshake     sent   TTFB  download
      200     4.0    225.0     -229.0    229.0  226.0       0.0
      200     4.0    235.0     -239.0    239.0  235.0       1.0
      200     4.0    232.0     -236.0    236.0  233.0       0.0
      200     4.0    241.0     -245.0    245.0  241.0       1.0

     min:     4.0    225.0     -245.0    229.0  226.0       0.0
     avg:     4.0    233.2     -237.2    237.2  233.8       0.5
     med:     4.0    235.0     -236.0    239.0  235.0       1.0
     max:     4.0    241.0     -229.0    245.0  241.0       1.0
     dev:    0.0%     2.5%      -2.4%     2.4%   2.3%    100.0%
            requests: 4    samples: 4    failures: 0           

➜  curl-benchmark git:(master) python3 curl-benchmark.py -- -x 0.0.0.0:8001 "http://example.com"
              DNS      TCP        SSL  Request          Content
     Code  lookup  connect  handshake     sent   TTFB  download
      200     0.0      0.0        0.0      0.0  BIG         0.0
      200     0.0      0.0        0.0      0.0  BIG         0.0
      200     0.0      0.0        0.0      0.0  BIG         0.0
      200     0.0      0.0        0.0      0.0  BIG         0.0
      200     0.0      0.0        0.0      0.0  BIG         0.0

     min:     0.0      0.0        0.0      0.0  BIG         0.0
     avg:     0.0      0.0        0.0      0.0  BIG         0.0
     med:     0.0      0.0        0.0      0.0  BIG         0.0
     max:     0.0      0.0        0.0      0.0  BIG         0.0
     dev:    0.0%     0.0%       0.0%     0.0%   0.8%      0.0%
            requests: 5    samples: 5    failures: 0           
```

The proxies are 100% okay,
```
➜  curl-benchmark git:(master) curl ifconfig.co
103.111.XX.XXX
➜  curl-benchmark git:(master) curl -x 0.0.0.0:8001 ifconfig.co
185.196.XXX.XXX
➜  curl-benchmark git:(master) curl -x 0.0.0.0:8002 ifconfig.co
194.32.XXX.XXX
➜  curl-benchmark git:(master) curl -x 104.XXX.XXX.XXX:1234 ifconfig.co
209.107.XXX.XXX
```

```
➜  curl-benchmark git:(master) curl --version   
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

**Comment by mildsunrise** [comment]
Oh! There's a bug in the «SSL handshake» and «Request sent» columns, which should be showing 0. I have fixed it :)

But other than that, this looks normal to me. In the second command the values are too big to be shown, please [add a space before `TTFB` in this line](https://github.com/jmendeth/curl-benchmark/blob/af258cdc6b66a3177e044b0d04417f1a74a6bdf7/curl-benchmark.py#L55).

**Comment by entrptaher** [comment]
I guess this works for now. I will reopen if issue persists.

```
➜  curl-benchmark git:(master) python3 curl-benchmark.py -- -x XXX.XXX.XXX.XXX:1234 https://ifconfig.co 
              DNS      TCP        SSL  Request          Content
     Code  lookup  connect  handshake     sent   TTFB  download
      200     0.0    259.0     2894.0      0.0  824.0       0.0
      200     0.0    240.0     3077.0      0.0  810.0       0.0
      200     0.0    243.0     2784.0      0.0  802.0       0.0
      ...

     min:     0.0    240.0     1091.0      0.0  494.0       0.0
     avg:     0.0    254.9     1725.5      0.2  716.4       0.1
     med:     0.0    251.0     1401.0      0.0  648.0       0.0
     max:     0.0    332.0     3077.0      1.0  999.0       1.0
     dev:    0.0%     7.1%      40.8%   236.6%  18.0%    316.2%
           requests: 33    samples: 33    failures: 0
```
